[phases.setup]
nixPkgs = ["python311", "cairo", "pango", "gdk-pixbuf", "libffi", "shared-mime-info"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "uvicorn main:app --host 0.0.0.0  --port $PORT"
